### create account
POST http://localhost:8080/account
Content-Type: application/json

{
    "userId": 1,
    "initBalance": 100
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
    "userId": 1,
    "accountNumber": "1000000000"
}