### create account
POST http://localhost:8080/account
Content-Type: application/json

{
    "userId": 1,
    "initBalance": 1000000
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
    "userId": 1,
    "accountNumber": "0158446948"
}

### get accountList
GET http://localhost:8080/account?user_id=4